//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.MainModule.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationLayer.MainModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        internal static string ControlFactory_GetGroupBoxFromContainer___ {
            get {
                return ResourceManager.GetString("ControlFactory_GetGroupBoxFromContainer___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        internal static string ControlManager_GetGroupBoxFromContainer___ {
            get {
                return ResourceManager.GetString("ControlManager_GetGroupBoxFromContainer___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error during loading XML file with form data..
        /// </summary>
        internal static string MainForm_LoadXmlToolStripMenuItemClick_Error_during_loading_XML_file_with_form_data_ {
            get {
                return ResourceManager.GetString("MainForm_LoadXmlToolStripMenuItemClick_Error_during_loading_XML_file_with_form_da" +
                        "ta_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_LoadXmlToolStripMenuItemClick_XML_Files____xml____xml_All_Files__________ {
            get {
                return ResourceManager.GetString("MainForm_LoadXmlToolStripMenuItemClick_XML_Files____xml____xml_All_Files_________" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error during processing XSD schema:.
        /// </summary>
        internal static string MainForm_LoadXSDToolStripMenuItemClick_Error_during_processing_XSD_schema_ {
            get {
                return ResourceManager.GetString("MainForm_LoadXSDToolStripMenuItemClick_Error_during_processing_XSD_schema_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XSD Files (*.xsd)|*.xsd|All Files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_LoadXSDToolStripMenuItemClick_XSD_Files____xsd____xsd_All_Files__________ {
            get {
                return ResourceManager.GetString("MainForm_LoadXSDToolStripMenuItemClick_XSD_Files____xsd____xsd_All_Files_________" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Error {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error during saving XML file with data to the file..
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Error_during_saving_XML_file_with_data_to_the_file_ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Error_during_saving_XML_file_with_data_t" +
                        "o_the_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Form contains error(s)!.
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Form_contain_error_ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Form_contain_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save file as....
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_Save_file_as___ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_Save_file_as___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_SaveXmlAsToolStripMenuItemClick_XML_files____xml____xml_All_files__________ {
            get {
                return ResourceManager.GetString("MainForm_SaveXmlAsToolStripMenuItemClick_XML_files____xml____xml_All_files_______" +
                        "___", resourceCulture);
            }
        }
    }
}
