//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Data.ServiceAgent.GtInterfaceWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gtmotive.com/", ConfigurationName="GtInterfaceWS.GtInterfaceWSSoap")]
    public interface GtInterfaceWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://gtmotive.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gtmotive.com/GTIWS", ReplyAction="*")]
        Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSResponse GTIWS(Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GTIWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GTIWS", Namespace="http://gtmotive.com/", Order=0)]
        public Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequestBody Body;
        
        public GTIWSRequest() {
        }
        
        public GTIWSRequest(Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gtmotive.com/")]
    public partial class GTIWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public GTIWSRequestBody() {
        }
        
        public GTIWSRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GTIWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GTIWSResponse", Namespace="http://gtmotive.com/", Order=0)]
        public Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSResponseBody Body;
        
        public GTIWSResponse() {
        }
        
        public GTIWSResponse(Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gtmotive.com/")]
    public partial class GTIWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GTIWSResult;
        
        public GTIWSResponseBody() {
        }
        
        public GTIWSResponseBody(string GTIWSResult) {
            this.GTIWSResult = GTIWSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GtInterfaceWSSoapChannel : Infraestructure.Data.ServiceAgent.GtInterfaceWS.GtInterfaceWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GtInterfaceWSSoapClient : System.ServiceModel.ClientBase<Infraestructure.Data.ServiceAgent.GtInterfaceWS.GtInterfaceWSSoap>, Infraestructure.Data.ServiceAgent.GtInterfaceWS.GtInterfaceWSSoap {
        
        public GtInterfaceWSSoapClient() {
        }
        
        public GtInterfaceWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GtInterfaceWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GtInterfaceWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GtInterfaceWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSResponse Infraestructure.Data.ServiceAgent.GtInterfaceWS.GtInterfaceWSSoap.GTIWS(Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequest request) {
            return base.Channel.GTIWS(request);
        }
        
        public string GTIWS(string xml) {
            Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequest inValue = new Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequest();
            inValue.Body = new Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSRequestBody();
            inValue.Body.xml = xml;
            Infraestructure.Data.ServiceAgent.GtInterfaceWS.GTIWSResponse retVal = ((Infraestructure.Data.ServiceAgent.GtInterfaceWS.GtInterfaceWSSoap)(this)).GTIWS(inValue);
            return retVal.Body.GTIWSResult;
        }
    }
}
